site_name: Runes
site_url: https://daymonri.github.io/runes/
site_description: A brief interpretation of the runes.
site_author: Alexey Frolov
repo_url: https://github.com/daymonri/runes.git

theme: material

nav:
    - Феху1: fehu.md
    - Уруз: uruz.md
    - Турисаз: turisaz.md
    - Ансуз: ansuz.md
    - Райдо: raido.md
    - Кеназ: kenaz.md
    - Гебо: gebo.md
    - Виньо: winjo.md
    - Хагалаз: hagalaz.md
    - Наудис: nautiz.md
    - Иса: isa.md
    - Йера: jera.md
    - Эйваз: ihwaz.md
    - Перт: pert.md
    - Альгиз: algiz.md
    - Сол: sol.md
    - Тейваз: teivaz.md
    - Беркана: berkana.md
    - Эваз: evaz.md
    - Манназ: mannaz.md
    - Лагуз: laguz.md
    - Ингуз: inguz.md
    - Дагаз: dagaz.md
    - Одал: odal.md
    - Руна Одина: runa_odina.md
    - Ключевые образы: obrazi.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

markdown_extensions:
  - attr_list
  - md_in_html

markdown_extensions:
  - toc:
      title: Содержание

copyright: Copyright &copy; 2025